robot:
  name: g1
  model_path: "robots/g1_description/mjcf/scene_29dof.xml"
  urdf_path: "robots/g1_description/mjcf/g1_29dof.xml"

  ee_feet:
    right_feet_ee: "right_ankle_roll_link"
    left_feet_ee: "left_ankle_roll_link"
  pelvis_body_name: "pelvis"
  torso_body_name: "torso_link"
  waist_lower_body_name: "waist_roll_link"

reference_trajectory:
  q_ref: "data/g1/standing/q_standing.csv"
  v_ref: "data/g1/standing/v_standing.csv"
  contact_schedule: "data/g1/standing/contact_standing.csv"

mpc:
  horizon: 25
  dt: 0.02
  physics_dt: 0.02
  gravity: [0.0, 0.0, -0.05]
  sim_steps: 50
  contact_impratio: 100.0

  cost_weights:
    posture:
      weight: 50.0
      terminal_weight: 100.0

    control:
      R_control: 0.01

    W_height: 100.0
    W_vel: 0.0
    W_joint_vel: 0.1
    W_upright: 20.0
    w_balance: 30.0
    balance_time_constant: 0.2
    W_pelvis_feet: 0.0
    W_walk: 0.0
    speed_goal: 0.0

  norm_types:
    posture:
      type: 0
      p: 0.0
      q: 1.0
    height:
      type: 0
      p: 0.0
      q: 1.0
    balance:
      type: 0
      p: 0.0
      q: 1.0
    pelvis_feet:
      type: 8
      p: 0.05
      q: 1.0
    upright:
      type: 0
      p: 0.0
      q: 1.0
    velocity:
      type: 0
      p: 0.0
      q: 1.0
    joint_vel:
      type: 0
      p: 0.0
      q: 1.0
    control:
      type: 0
      p: 0.0
      q: 1.0
    walk:
      type: 7
      p: 0.5
      q: 3.0

  ilqr_settings:
    initial_regularization: 1.0e-3
    max_iterations: 20
    tolerance: 1.0e-4
    reg_min: 1.0e-4
    reg_max: 1.0e6
    reg_increase_factor: 10.0
    reg_decrease_factor: 10.0
    trust_region_good: 0.5
    trust_region_poor: 0.25
    num_line_search_steps: 12
    min_linesearch_step: 1.0e-3
    line_search_tolerance: 1.0e-6
    quu_regularization: 1.0e-2
    convergence_threshold: 1.0e-8
    fd_tolerance: 1.0e-6
    fd_mode: 0
    debug_qacc_enable: false
    debug_qacc_threshold: 1.0e4
    debug_qacc_max_logs: 20

paths:
  logs_dir: "logs"
  results_dir: "results"

logging:
  verbose: true
  save_trajectories: true
  results_path: "results"

visualization:
  enable_rerun: false
