name: humanoid-mpc
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - scipy>=1.10.0
  
  # MuJoCo Python bindings (includes C++ MuJoCo automatically)
  - mujoco>=3.0.0
  
  # Pinocchio and CasADi for automatic differentiation
  - pinocchio>=2.6.0
  - casadi>=3.6.0
  
  # C++ build tools and libraries (cross-platform)
  - cmake>=3.20
  - ninja  # Fast build system
  - pkg-config
  
  # C++ compiler toolchain (cross-platform)
  - cxx-compiler  # Automatically installs appropriate C++ compiler for platform
  - eigen  # Linear algebra library (C++)
  - glfw  # OpenGL windowing (C++)
  
  # Development tools
  - yaml-cpp
  - ipython
  - pytest
  
  # Visualization libraries
  - seaborn
  - plotly
  
  # Build utilities
  - make  # For Linux/macOS
  - pip